//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Data.EF
{
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Find3dPrinting.Models;

    public partial class Find3dPrintingDBContext : DbContext
    {
        public Find3dPrintingDBContext()
            : base("Find3dPrintingEntities")
        {
            
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BoxSize>().HasKey<long>(k => k.BoxSizes_id);
            modelBuilder.Entity<ComputeTechnology>().HasKey<long>(k => k.ComputeTechnologies_id);
            modelBuilder.Entity<Delivery>().HasKey<long>(k => k.Delivery_id);
            modelBuilder.Entity<Delivery_Manufacturers>().HasKey<long>(k => k.Delivery_Manufacturers_id);
            modelBuilder.Entity<Manufacturer>().HasKey<long>(k => k.Manufacturers_id);
            modelBuilder.Entity<Manufacturers_Printers>().HasKey<long>(k => k.Manufacturers_Printers_id);
            modelBuilder.Entity<Manufacturers_Services>().HasKey<long>(k => k.Manufacturers_Services_id);
            modelBuilder.Entity<Material>().HasKey<long>(k => k.Materials_id);
            modelBuilder.Entity<Payment>().HasKey<long>(k => k.Payments_id);
            modelBuilder.Entity<Payments_Manufacturers>().HasKey<long>(k => k.Payments_Manufacturers_id);
            modelBuilder.Entity<Printer>().HasKey<long>(k => k.Printers_id);
            modelBuilder.Entity<Service>().HasKey<long>(k => k.Services_id);
            modelBuilder.Entity<User>().HasKey<long>(k => k.Users_id);

        }

        public DbSet<BoxSize> BoxSizes { get; set; }
        public DbSet<ComputeTechnology> ComputeTechnologies { get; set; }
        public DbSet<Delivery> Deliveries { get; set; }
        public DbSet<Delivery_Manufacturers> Delivery_Manufacturers { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Manufacturers_Printers> Manufacturers_Printers { get; set; }
        public DbSet<Manufacturers_Services> Manufacturers_Services { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Payments_Manufacturers> Payments_Manufacturers { get; set; }
        public DbSet<Printer> Printers { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
