//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxSize
    {
        public long BoxSizesId { get; set; } // BoxSizes_id (Primary key)
        public float XDimmSize { get; set; } // X_dimm_size
        public float YDimmSize { get; set; } // Y_dimm_size
        public float ZDimmSize { get; set; } // Z_dimm_size
        public float ScallingRatio { get; set; } // ScallingRatio

        // Reverse navigation
        public virtual ICollection<Printer> Printers { get; set; } // Printers.FK_Printers_BoxSizes

        public BoxSize()
        {
            Printers = new List<Printer>();
        }
    }
}
