//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputeTechnology
    {
        public long ComputeTechnologiesId { get; set; } // ComputeTechnologies_id (Primary key)
        public string ComputeTechnology_ { get; set; } // ComputeTechnology

        // Reverse navigation
        public virtual ICollection<Printer> Printers { get; set; } // Printers.FK_Printers_ComputeTechnologies

        public ComputeTechnology()
        {
            Printers = new List<Printer>();
        }
    }
}
