//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryManufacturers
    {
        public long DeliveryManufacturersId { get; set; } // Delivery_Manufacturers_id (Primary key)
        public long DeliveryId { get; set; } // Delivery_id
        public long ManufacturerId { get; set; } // Manufacturer_id

        // Foreign keys
        public virtual Delivery Delivery { get; set; } // FK_Delivery_Manufacturers_Delivery
        public virtual Manufacturer Manufacturer { get; set; } // FK_Delivery_Manufacturers_Manufacturers
    }
}
