//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Manufacturers
    {
        public long Delivery_Manufacturers_id { get; set; }
        public long Delivery_id { get; set; }
        public long Manufacturer_id { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
