//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.Delivery_Manufacturers = new HashSet<Delivery_Manufacturers>();
            this.Manufacturers_Printers = new HashSet<Manufacturers_Printers>();
            this.Payments_Manufacturers = new HashSet<Payments_Manufacturers>();
        }
    
        public long Manufacturers_id { get; set; }
        public string OrganizationName { get; set; }
        public long User_id { get; set; }
    
        public virtual ICollection<Delivery_Manufacturers> Delivery_Manufacturers { get; set; }
        public virtual ICollection<Manufacturers_Printers> Manufacturers_Printers { get; set; }
        public virtual Manufacturers_Services Manufacturers_Services { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Payments_Manufacturers> Payments_Manufacturers { get; set; }
    }
}
