//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public long ManufacturersId { get; set; } // Manufacturers_id (Primary key)
        public string OrganizationName { get; set; } // OrganizationName
        public long UserId { get; set; } // User_id

        // Reverse navigation
        public virtual ICollection<DeliveryManufacturers> DeliveryManufacturers { get; set; } // Delivery_Manufacturers.FK_Delivery_Manufacturers_Manufacturers
        public virtual ICollection<ManufacturersPrinters> ManufacturersPrinters { get; set; } // Manufacturers_Printers.FK_Manufacturers_Printers_Manufacturers
        public virtual ICollection<PaymentsManufacturers> PaymentsManufacturers { get; set; } // Payments_Manufacturers.FK_Payments_Manufacturers_Manufacturers
        public virtual ManufacturersServices ManufacturersServices { get; set; } // Manufacturers_Services.FK_Manufacturers_Services_Manufacturers

        // Foreign keys
        public virtual User User { get; set; } // FK_Manufacturers_Users

        public Manufacturer()
        {
            DeliveryManufacturers = new List<DeliveryManufacturers>();
            ManufacturersPrinters = new List<ManufacturersPrinters>();
            PaymentsManufacturers = new List<PaymentsManufacturers>();
        }
    }
}
