//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturersServices
    {
        public long ManufacturersServicesId { get; set; } // Manufacturers_Services_id (Primary key)
        public long ManufacturerId { get; set; } // Manufacturer_id
        public long ServiceId { get; set; } // Service_id

        // Foreign keys
        public virtual Service Service { get; set; } // FK_Manufacturers_Services_Services
    }
}
