//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturersPrinters
    {
        public long ManufacturersPrintersId { get; set; } // Manufacturers_Printers_id (Primary key)
        public long ManufacturerId { get; set; } // Manufacturer_id
        public long PrinterId { get; set; } // Printer_id

        // Foreign keys
        public virtual Manufacturer Manufacturer { get; set; } // FK_Manufacturers_Printers_Manufacturers
        public virtual Printer Printer { get; set; } // FK_Manufacturers_Printers_Printers
    }
}
