//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public long MaterialsId { get; set; } // Materials_id (Primary key)
        public string Material_ { get; set; } // Material

        // Reverse navigation
        public virtual ICollection<Printer> Printers { get; set; } // Printers.FK_Printers_Materials

        public Material()
        {
            Printers = new List<Printer>();
        }
    }
}
