//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Printers = new HashSet<Printer>();
        }
    
        public long Materials_id { get; set; }
        public string Material1 { get; set; }
    
        public virtual ICollection<Printer> Printers { get; set; }
    }
}
