//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Payments_Manufacturers = new HashSet<Payments_Manufacturers>();
        }
    
        public long Payments_id { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual ICollection<Payments_Manufacturers> Payments_Manufacturers { get; set; }
    }
}
