//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsManufacturers
    {
        public long PaymentsManufacturersId { get; set; } // Payments_Manufacturers_id (Primary key)
        public long PaymentId { get; set; } // Payment_id
        public long ManufacturerId { get; set; } // Manufacturer_id

        // Foreign keys
        public virtual Manufacturer Manufacturer { get; set; } // FK_Payments_Manufacturers_Manufacturers
        public virtual Payment Payment { get; set; } // FK_Payments_Manufacturers_Payments
    }
}
