//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public long PrintersId { get; set; } // Printers_id (Primary key)
        public int NozzleThickness { get; set; } // NozzleThickness
        public string PrinterName { get; set; } // PrinterName
        public long BoxSizeId { get; set; } // BoxSize_id
        public long MaterialId { get; set; } // Material_id
        public long ComputeTechnologyId { get; set; } // ComputeTechnology_id

        // Reverse navigation
        public virtual ICollection<ManufacturersPrinters> ManufacturersPrinters { get; set; } // Manufacturers_Printers.FK_Manufacturers_Printers_Printers

        // Foreign keys
        public virtual BoxSize BoxSize { get; set; } // FK_Printers_BoxSizes
        public virtual ComputeTechnology ComputeTechnology { get; set; } // FK_Printers_ComputeTechnologies
        public virtual Material Material { get; set; } // FK_Printers_Materials

        public Printer()
        {
            ManufacturersPrinters = new List<ManufacturersPrinters>();
        }
    }
}
