//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find3dPrinting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UsersId { get; set; } // Users_id (Primary key)
        public string Email { get; set; } // Email
        public string Password { get; set; } // Password
        public string PhoneNumber { get; set; } // PhoneNumber

        // Reverse navigation
        public virtual Manufacturer Manufacturer { get; set; } // Manufacturers.FK_Manufacturers_Users
    }
}
